### ISSUE TITLE
Split ModBase in a different github repo for better modding

### ISSUE THREAD

**Issue by elboletaire** [skwasjer/CitiesSkylines#1]
Splitting them in different repositories allow us to use it as a git submodule in our project and also will be better for you to manage the issues.

**Comment by skwasjer** [comment]
You are right, I will do that later :+1:

**Comment by elboletaire** [comment]
Also, yesterday I tried to add your ModBase to my Mod, but I couldn't due to some errors (probably I'm too newbie to use this methodology and I'm doing something wrong). I'll try to open a new issue explaining all the troubles that I found, how I solved and where am currently blocked.

**Comment by elboletaire** [comment]
BTW, I'm not sure if you're aware of this other Mod for better modding (it's a little bit more advanded than yours, maybe you could merge both projects): https://github.com/DlkGames/SkylineToolkit

**Comment by skwasjer** [comment]
Looks like a far more expansive project then I am willing to go for, at least for the time being. I like to keep things simple and small. 

In their library, it looks like alot of wrapping of Collosal's libraries is being done, which may break at one point when the game receives updates, or generally just adds alot of noise imo. It really depends on the goals and vision of its collaborators and users. Interesting for sure, it may become a modders dream, but on the flipside also not something that may appeal to smalltime modders. 

My focus for the time being is to provide a minimalistic set of base classes. I do have some more ideas to add, but main focus will remain keeping things small. Perhaps even a new project for fancy stuff...

**Comment by elboletaire** [comment]
I also think is a good idea to keep it simple. Maybe you could think in a way to achieve some of the SkylineToolkit functionality by focus in extending your ModBase.

For example, this mod can be extended: https://github.com/Rychard/CityWebServer

As said, I'm really newbie and I don't know how much difficult can it be, nor the technological problems that can occur when doing this kind of things.

**Comment by skwasjer** [comment]
Renamed this repo to CSAutosave and moved ModBase over to 
https://github.com/skwasjer/CSModBase. Note that the readme is slightly off now, I need to correct that still.

**Comment by elboletaire** [comment]
Nice! :+1:
