### ISSUE TITLE
System & System.Configuration are also required references

### ISSUE THREAD

**Issue by elboletaire** [skwasjer/CitiesSkylines#2]
In the readme of ModSettings you say to add as references:
- ICities.dll
- Assembly-CSharp.dll
- ColossalManaged.dll
- UnityEngine.dll
- UnityEngine.UI.dll

But when I tried to build my project after adding your files I saw that also are required:
- System.dll
- System.Configuration.dll

**Comment by skwasjer** [comment]
Fair enough, I will update the docs, to add a section with required .NET references. I guess I am too lazy because Resharper just adds all that for me :smile:

**Comment by elboletaire** [comment]
Well it's easy to see but I think that the docs should be useful for every kind of development skill (I'm a newbie but there's people more newbie out there xD).

**Comment by skwasjer** [comment]
Appreciate the comments! I agree it should be as easy and clear as possible, it was the intention of the base classes to take away base work for each new plugin. I have some pending commits coming and after that I will split off the ModBase project to a new repo.

**Comment by elboletaire** [comment]
If you do that during today I'll wait for the changes before posting my issue.
